[project]
authors = []
channels = ["conda-forge", "https://conda.modular.com/max"]
description = ""
name = ""
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]


[dependencies]
max = ">=24.6.0,<25"